[package]
name = "crawler"
version = "0.1.0"
authors = ["di <dwu@uuzu.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.5.0"
surf = "1.0.3"